pipeline:

  create-package:
    image: fpfis/php56
    commands:
      - tar cz web > ${DRONE_REPO_NAME}-${DRONE_TAG}.tar.gz
    when:
      event: tag

  github_release:
    image: plugins/github-release
    files:
      - ${DRONE_REPO_NAME}-${DRONE_TAG}.tar.gz
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
    secrets:
      - source: github_api_token 
        target: api_key
    when:
      event: tag
