services:
  mysql:
    image: fpfis/mysql56

pipeline:

  get-sanitzed-dump:
    image: fpfis/drone-plugin-asda
    target: dump.sql
    website: ${DRONE_REPO_NAME%%-reference}
    secrets: [ asda_url ]
    when:
      branch: [ production, acceptance, test ]

  import-dump:
    image: fpfis/mysql56
    commands:
      - mysql -h mysql < dump.sql
