services:
  mysql:
    image: fpfis/mysql56

pipeline:
  fix-drupal:
    image: fpfis/php56-dev
    commands:
      - patch -i ../assets/drupal_get_path_alias-fix.patch -d web -p1

  get-sanitzed-dump:
    image: fpfis/drone-plugin-asda
    target: dump.sql
    website: ${DRONE_REPO_NAME%%-reference}
    secrets: [ asda_url ]
    when:
      branch: [ production, acceptance, test ]

  import-dump:
    image: fpfis/mysql56
    commands:
      - mysqladmin -h mysql create database
      - mysql database -h mysql < dump.sql

  setup-test-drupal:
    image: fpfis/php56-dev
    commands:
      - cp assets/settings.docker.php web/sites/default/settings.local.php


  test-drush:
    image: fpfis/php56-dev
    commands:
      - drush -r web updb -y
      - drush -r web rr
      - drush -r web updb -y
      - drush -r web fra -y
      - drush -r web status
      - drush -r web cc all
