services:
  mysql:
    image: percona/percona-server:5.6
    ports:
    - 3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      

pipeline:
  get-sanitzed-dump:
    image: fpfis/drone-plugin-asda
    target: dump.sql
    website: ${DRONE_REPO_NAME%%-reference}
    secrets: [ asda_url ]

  import-dump:
    image: percona/percona-server:5.6
    commands:
      - sleep 15
      - mysqladmin -h mysql -u root create database
      - mysql database -h mysql -u root < dump.sql
    when:
      event: push

  setup-test-drupal:
    image: fpfis/php71-dev
    commands:
      - cp assets/settings.docker.php web/sites/default/settings.local.php
    when:
      event: push

  test-upgrade-test:
    image: fpfis/php71-dev:latest
    commands:
      - drush -r web cc all
      - drush -r web rr --no-cache-clear
      - drush -r web cc all
      - drush -r web fra -y
      - drush -r web updb -y
      - drush -r web status
      - drush -r web cc all
    when:
      event: push

  slack-notify-deploy:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: ci
    username: fpfisbot
    icon_url: https://avatars0.githubusercontent.com/u/23079543?v=3&s=400
    when:
      event: push
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        {{repo.name}}@{{build.branch}} <{{build.link}}|passed> the upgrade test.
      {{else}}
        {{repo.name}}@{{build.branch}} <{{build.link}}|failed> the upgrade test.
      {{/success}}

  create-deploy-acceptance:
    image: fpfis/drone-plugin-github-deploy
    state: create
    deploy_environment: [ acceptance ]
    secrets: [ github_api_token ]
    automerge: false
    when:
      event: push
      branch: [feature/php7_acceptance]

 

  # Begin deployment
 
  mark-commit:
    image: fpfis/php71-dev
    commands:
      - echo ${DRONE_BUILD_NUMBER} > web/.dronebuildnumber
      - echo ${DRONE_COMMIT_SHA} > web/.commit
    when:
      event: push
     
         
# Push to deploy server and sync platform/sites/default folder from live environment
  deploy-test:
    image: fpfis/drone-plugin-git-deploy
    source: web
    target_folder: website
    secrets:
      - source: target_repo_acceptance
        target: target_repo
      - source: deploy_key_acceptance
        target: deploy_key
    clean: false
    message: Deployed ${DRONE_COMMIT_SHA} from ${DRONE_REPO_ORG}/${DRONE_REPO_NAME}@${DRONE_BRANCH}
    excludes:
      - settings.php
      - settings.local.php
      - files
      - sites/all/modules/fpfis
    when:
      event: deployment
      environment: [ acceptance ]
      branch: [test, test/*, feature/*]

# Push to acceptance server :

  mark-deploy:
    image: fpfis/php71-dev
    commands:
    - echo ${DRONE_BUILD_NUMBER} > web/.dronedeploynumber
    when:  
      event: [ deployment ]
       
  align-website-environment:
    image: fpfis/php71-dev
    commands:
      - sleep 650 
      - drush -r web sql-drop --yes
      - drush -r web sqlc < dump.sql
      - drush -r web upwd 1 --password="$${UID1_ACCEPTANCE}"
      - drush -r web vset maintenance_mode 1
    when:
      event: deployment
      environment: [ acceptance]
  site-upgrade:
    image: fpfis/php71-dev:latest
    commands:
      - wget https://github.com/ec-europa/platform-deploy/archive/fpfis-conf/2.4.tar.gz -O -|tar --strip 1 -xzvC website
      - rm -f website/sites/sites.php
      - drush -r web cc all
      - drush -r webs rr --no-cache-clear
      - drush -r web cc all
      - drush -r web fra -y --force
      - drush -r web updb -y
      - drush -r web en reroute_email -y
      - drush -r web status
      - drush -r web cc all
      - drush -r web vset maintenance_mode 0
    when:
      event: deployment
      environment: [ acceptance ]
    #  branch: [test, test/*, feature/*]


  slack-notify-deploy:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: ci
    username: fpfisbot
    icon_url: https://avatars0.githubusercontent.com/u/23079543?v=3&s=400
    when:
      event: deployment
      environment: [ acceptance, test ]
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        {{repo.name}}@{{build.branch}} <{{build.link}}|deployed> in ${DRONE_DEPLOY_TO}.
      {{else}}
        {{repo.name}}@{{build.branch}} <{{build.link}}|failed> to deploy in ${DRONE_DEPLOY_TO}.
      {{/success}}
